FROM mysql:latest

# export from phpmyadmin a .sql file
# and reaplce ./jb-45800-5-mission-3.sql with it
# then uncomment the following line
# COPY ./jb-45800-5-mission-3.sql /docker-entrypoint-initdb.d/
